// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLU1rEDPgvYqTMfQJz5So4o5vchqFshwU',
    appId: '1:893357478385:web:3daf00d2ae721f7b973450',
    messagingSenderId: '893357478385',
    projectId: 'hits-constituency-app',
    authDomain: 'hits-constituency-app.firebaseapp.com',
    storageBucket: 'hits-constituency-app.firebasestorage.app',
    measurementId: 'G-SHC7H0QDXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3GkuIfOKJPXaxn0-G_QCidYX6Ho-JaM',
    appId: '1:893357478385:android:25eb746115406b4f973450',
    messagingSenderId: '893357478385',
    projectId: 'hits-constituency-app',
    storageBucket: 'hits-constituency-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNd6y5o5P-fGgc0Ng5WP0duHIkraUAvEE',
    appId: '1:893357478385:ios:31d517b2428350b6973450',
    messagingSenderId: '893357478385',
    projectId: 'hits-constituency-app',
    storageBucket: 'hits-constituency-app.firebasestorage.app',
    iosBundleId: 'com.example.knowyourconst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNd6y5o5P-fGgc0Ng5WP0duHIkraUAvEE',
    appId: '1:893357478385:ios:31d517b2428350b6973450',
    messagingSenderId: '893357478385',
    projectId: 'hits-constituency-app',
    storageBucket: 'hits-constituency-app.firebasestorage.app',
    iosBundleId: 'com.example.knowyourconst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLU1rEDPgvYqTMfQJz5So4o5vchqFshwU',
    appId: '1:893357478385:web:813b03b921add500973450',
    messagingSenderId: '893357478385',
    projectId: 'hits-constituency-app',
    authDomain: 'hits-constituency-app.firebaseapp.com',
    storageBucket: 'hits-constituency-app.firebasestorage.app',
    measurementId: 'G-08ED7MY5QZ',
  );
}
